In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\af-matthias\miniconda3\envs\llm-zoomcamp\Lib\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\af-matthias\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
q1 = "Can I still join the course after the start date?"
v1 = model.encode(q1)

print(v1.shape)

(384,)


In [5]:
d = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)

In [7]:
similarity = model.similarity(v1, dv)
print(similarity)

tensor([[0.3233]])


In [21]:
v1.dot(dv)

np.float32(0.323324)

In [ ]:
# TEST
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]

# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sentences)
print(embeddings)
# [3, 384]

[[ 0.01919576  0.12008537  0.15959829 ... -0.00536282 -0.08109502
   0.05021341]
 [-0.01869034  0.0415187   0.07431547 ...  0.004866   -0.06190434
   0.03187511]
 [ 0.136502    0.08227322 -0.02526164 ...  0.08762049  0.03045843
  -0.01075752]]


In [19]:
q2 = "How to install Docker on Windows?"
v2 = model.encode(q2)
v2

array([-2.35677883e-02,  7.85555765e-02,  2.33792625e-02, -6.72475435e-03,
       -2.58874726e-02,  1.18256640e-02,  5.29527431e-04,  9.57366079e-03,
        6.23929128e-02,  2.91427094e-02, -4.18229997e-02, -6.62149265e-02,
       -2.76613347e-02,  5.41518740e-02, -1.92781650e-02, -2.46782135e-02,
       -2.89787864e-03,  8.40462074e-02,  1.03637632e-02, -6.35393988e-03,
       -1.20814100e-01,  1.80162862e-02, -5.70900701e-02, -7.92970881e-02,
       -9.25547816e-03, -3.24046090e-02, -1.95662733e-02, -2.65410803e-02,
       -9.41327959e-03,  4.31234725e-02, -2.08750162e-02, -7.86434039e-02,
        9.19373557e-02, -3.75263649e-03,  5.13071194e-02, -5.73638361e-03,
        5.61954305e-02,  3.73761216e-03, -6.88236579e-02, -4.57000434e-02,
        2.83076130e-02, -3.49764675e-02, -5.55221282e-04, -3.09770070e-02,
        4.34274971e-02, -4.48056757e-02,  6.84109777e-02,  4.14158509e-04,
        5.82685843e-02,  6.66982681e-02, -8.95875692e-02, -2.69941594e-02,
        1.06746368e-02, -

In [10]:
v2.dot(dv)

np.float32(0.019730454)

In [24]:
from ingest import load_faq_data

documents = load_faq_data()
len(documents)

1350

In [20]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

len(texts)

L = [3,4,5,6,74,8]

M = L[2:len(L)]
M

[5, 6, 74, 8]

In [23]:
from tqdm.auto import tqdm

batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [25]:
import numpy as np
X = np.array(vectors)

In [26]:
query = "Can I still join the course after the start date?"

v_query = model.encode(query)

In [ ]:
scores = X.dot(v_query)

array([ 0.4874059 ,  0.20991927,  0.7629411 , ..., -0.08637965,
        0.03759794, -0.03037034], shape=(1350,), dtype=float32)

In [29]:
scores = [X[i].dot(v_query) for i in range(len(X))]

In [ ]:
idx = np.argmax(scores)
idx, scores[idx]